### ISSUE TITLE
Inference fails with "File not found: synset.txt"

### ISSUE THREAD

**Issue by yuk0ga** [awslabs/djl-spring-boot-starter#8]
I am trying to implement an Object Detection app with Spring Boot and djl-spring-boot-starter, but I'm encountering the following error when the `predict()` function is called:

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at com.koga.jsugdjldemo.JsugDjlDemoApplication.main(JsugDjlDemoApplication.java:61) ~[classes/:na]
Caused by: ai.djl.translate.TranslateException: java.io.FileNotFoundException: File not found: /Users/username/.djl.ai/cache/repo/model/cv/object_detection/ai/djl/pytorch/ssd/300/resnet50/coco/0.0.1/synset.txt
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:166) ~[api-0.7.0.jar:na]
	at ai.djl.inference.Predictor.predict(Predictor.java:112) ~[api-0.7.0.jar:na]
	at com.koga.jsugdjldemo.JsugDjlDemoApplication.runInference(JsugDjlDemoApplication.java:82) ~[classes/:na]
	at com.koga.jsugdjldemo.JsugDjlDemoApplication.run(JsugDjlDemoApplication.java:74) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	... 5 common frames omitted
Caused by: java.io.FileNotFoundException: File not found: /Users/username/.djl.ai/cache/repo/model/cv/object_detection/ai/djl/pytorch/ssd/300/resnet50/coco/0.0.1/synset.txt
	at ai.djl.BaseModel.getArtifact(BaseModel.java:147) ~[api-0.7.0.jar:na]
	at ai.djl.BaseModel.getArtifactAsStream(BaseModel.java:153) ~[api-0.7.0.jar:na]
	at ai.djl.BaseModel.lambda$getArtifact$0(BaseModel.java:121) ~[api-0.7.0.jar:na]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[na:na]
	at ai.djl.BaseModel.getArtifact(BaseModel.java:118) ~[api-0.7.0.jar:na]
	at ai.djl.modality.cv.translator.BaseImageTranslator$SynsetLoader.load(BaseImageTranslator.java:222) ~[api-0.7.0.jar:na]
	at ai.djl.modality.cv.translator.ImageClassificationTranslator.prepare(ImageClassificationTranslator.java:48) ~[api-0.7.0.jar:na]
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:132) ~[api-0.7.0.jar:na]
	... 9 common frames omitted
```

Things I have done:
1. cloned djl-spring-boot-starter and ran `./mvnw install`
2. included the djl-spring-boot-starter-autoconfigure dependency in my pom.xml
3. edited my application.yml as follows:
```
djl:
  # Define application type
  application-type: OBJECT_DETECTION
  # Define input data type, a model may accept multiple input data type
  input-class: ai.djl.modality.cv.Image
  # Define output data type, a model may generate different out put
  output-class: ai.djl.modality.cv.output.DetectedObjects
  arguments:
    threshold: 0.2
```

How can I fix this? Thanks in advance.

**Comment by shapirov103** [comment]
Hello, can you please attached the pom file with version indication of DJL auto-configure. I assume you are using pytorch dependency starter.

**Comment by yuk0ga** [comment]
Hi, thank you for your response. 
Below is my pom file, and I am using macOS Catalina v10.15.6
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.4.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.user</groupId>
	<artifactId>jsug-djl-demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>jsug-djl-demo</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<djl.version>0.7.0</djl.version>
		<java.version>11</java.version>
		<jna.version>5.3.0</jna.version>
		<spring-cloud.version>Hoxton.SR8</spring-cloud.version>
	</properties>

	<repositories>
		<repository>
			<id>djl.ai</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			<groupId>ai.djl</groupId>
			<artifactId>api</artifactId>
		</dependency>
		<dependency>
			<groupId>net.java.dev.jna</groupId>
			<artifactId>jna</artifactId>
			<version>${jna.version}</version>      <!-- overrides default spring boot version to comply with DJL -->
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
		<dependency>
			<groupId>ai.djl.spring</groupId>
			<artifactId>djl-spring-boot-starter-autoconfigure</artifactId>
			<version>0.7-SNAPSHOT</version>
		</dependency>
<!--		<dependency>-->
<!--			<groupId>ai.djl.spring</groupId>-->
<!--			<artifactId>djl-spring-boot-starter-mxnet-auto</artifactId>-->
<!--			<version>0.7-SNAPSHOT</version> &lt;!&ndash; e.g. 0.2 and above &ndash;&gt;-->
<!--		</dependency>-->
		<dependency>
			<groupId>ai.djl.spring</groupId>
			<artifactId>djl-spring-boot-starter-pytorch-auto</artifactId>
			<version>0.7-SNAPSHOT</version> <!-- e.g. 0.2 and above -->
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>ai.djl</groupId>
				<artifactId>bom</artifactId>
				<version>${djl.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

**Comment by shapirov103** [comment]
To be honest, I am struggling to reproduce your issue. I used your pom and application.yml and ran a few sample detections successfully. I am also using macOS but lower version, so that is one difference.

One thing to try on your side is to see if the console sample that is part of the starter works for you. If you update it now you can see that it is very close to you configuration (both pom.xml and application.yml). If you run (assuming in the root of the project):
```
cd djl-spring-boot-console-sample
../mvnw clean package
 java -jar target/djl-spring-boot-console-sample-0.7-SNAPSHOT.jar
```
Do you see the same error?

**Comment by yuk0ga** [comment]
Actually, I was using the exact code (`ConsoleApplication.java` and `application.yml`) from the console sample, in a new project. 

But I just pulled the latest version of the console sample, and modified my own project accordingly and now it works!🎉

This problem is probably reproduce-able  if you un-comment the following code in `ConsoleApplication.java`
```
//	@SuppressWarnings("rawtypes")
//	@Bean
//	public Translator translator() {
//		return ImageClassificationTranslator.builder()
//				.addTransform(new ToTensor())
//				.optFlag(Image.Flag.GRAYSCALE)
//				.optApplySoftmax(true)
//				.build();
//	}
```
I see that you have commented out this code on the latest commit, along with the `urls` on `application.yml`. I'm guessing these are only required for the doodle sample, am I right?

**Comment by shapirov103** [comment]
Fantastic. Yes, the translator was added by me and it was really needed only for the doodle model (https://djl.ai/website/demo.html scroll down). It was left in the code to demo that you have ability to define a bean for custom translator and it will be picked up by auto-configuration with no extra effort.

I am going to close this issue then, if you see any problem in the future again, we can reopen.
